#!/bin/zsh

repo_url="https://github.com/jbrannlund/nvim" 
directory_name=~/.config/nvim 

# Function to check if a directory exists
directory_exists() {
  [[ -d "$1" ]]
}

# Function to prompt user for deletion
prompt_delete() {
  read -r "?Directory already exists. Delete it? [y/N] " response
  case "$response" in
    [yY][eE][sS]|[yY])
      rm -rf "$1"
      ;;
    *)
      echo "Exiting without cloning."
      exit 0
      ;;
  esac
}

# Main script
if directory_exists "$directory_name"; then
  prompt_delete "$directory_name"
fi

# Clone the repository
git clone "$repo_url" "$directory_name"

